# Generated by Django 5.1.3 on 2024-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flip',
            name='outcome_rating',
            field=models.IntegerField(default=0),
        ),
    ]
