# Generated by Django 5.1.3 on 2024-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0002_alter_flip_outcome_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
