# Generated by Django 5.1.3 on 2024-11-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0004_flip_content_flip_created_at_flip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flip',
            name='content',
        ),
    ]
