# Generated by Django 5.1.3 on 2024-11-25 01:23

import Flips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0005_remove_flip_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='uuid',
            field=models.CharField(default=Flips.models.gen_id, max_length=256),
        ),
    ]
