# Generated by Django 5.1.3 on 2024-11-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0006_flip_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='outcome',
            field=models.IntegerField(default=0),
        ),
    ]
