# Generated by Django 5.1.3 on 2024-11-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0007_flip_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='flip',
            name='is_flipped',
            field=models.BooleanField(default=False),
        ),
    ]
