# Generated by Django 5.1.3 on 2024-11-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0008_flip_is_flipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flip',
            name='is_flipped',
        ),
    ]
