# Generated by Django 5.1.3 on 2024-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0009_remove_flip_is_flipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flip',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
