# Generated by Django 5.1.3 on 2024-11-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flips', '0011_alter_flip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flip',
            name='comment',
        ),
    ]
